version: "3"
services:
  db:
    image: "postgres"
    container_name: "my_ktor_postgres"
    environment:
      - POSTGRES_USER=ktor
      - POSTGRES_PASSWORD=ktor
      - POSTGRES_DB=ktor_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql